import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, mkdir, writeFile, rm, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { bundle } from "./cli.js";

let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), "skills-cli-"));
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

const writeFixture = async (relPath: string, content: string | Uint8Array): Promise<void> => {
  const full = join(tempDir, relPath);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, content);
};

const importGeneratedBundle = async (filePath: string): Promise<Record<string, string>> => {
  // Strip the type annotation if any and eval the export to inspect it.
  const src = await readFile(filePath, "utf-8");
  const match = src.match(/export const skillsBundle\s*=\s*(\{[\s\S]*?\});/);
  if (!match) throw new Error(`Could not parse generated bundle: ${filePath}`);
  return JSON.parse(match[1]!) as Record<string, string>;
};

describe("bundle CLI logic", () => {
  it("bundles each skill folder's SKILL.md and references/", async () => {
    await writeFixture("skills/code-review/SKILL.md", "# code-review");
    await writeFixture("skills/code-review/references/style.md", "# style");
    await writeFixture("skills/commit-message/SKILL.md", "# commit");

    const out = join(tempDir, "out.ts");
    await bundle(join(tempDir, "skills"), out);
    const bundleObj = await importGeneratedBundle(out);

    expect(Object.keys(bundleObj).sort()).toEqual([
      "skills/code-review/SKILL.md",
      "skills/code-review/references/style.md",
      "skills/commit-message/SKILL.md",
    ]);
    expect(bundleObj["skills/code-review/SKILL.md"]).toBe("# code-review");
  });

  it("skips folders without SKILL.md (non-skill folders)", async () => {
    await writeFixture("skills/code-review/SKILL.md", "# skill");
    await writeFixture("skills/_shared/utils.md", "# not a skill");
    await writeFixture("skills/README.md", "# top-level docs");

    const out = join(tempDir, "out.ts");
    await bundle(join(tempDir, "skills"), out);
    const bundleObj = await importGeneratedBundle(out);

    expect(Object.keys(bundleObj)).toEqual(["skills/code-review/SKILL.md"]);
  });

  it("skips hidden directories and node_modules", async () => {
    await writeFixture("root/skills/foo/SKILL.md", "# foo");
    await writeFixture("root/.claude/skills/bar/SKILL.md", "# claude skill, ignore me");
    await writeFixture("root/node_modules/@pkg/skills/baz/SKILL.md", "# vendored, ignore me");

    const out = join(tempDir, "out.ts");
    await bundle(join(tempDir, "root"), out);
    const bundleObj = await importGeneratedBundle(out);

    expect(Object.keys(bundleObj)).toEqual(["root/skills/foo/SKILL.md"]);
  });

  it("warns and skips non-text files in references/scripts/assets", async () => {
    await writeFixture("skills/foo/SKILL.md", "# foo");
    await writeFixture("skills/foo/assets/logo.png", new Uint8Array([0x89, 0x50, 0x4e, 0x47]));

    const out = join(tempDir, "out.ts");
    await bundle(join(tempDir, "skills"), out);
    const bundleObj = await importGeneratedBundle(out);

    expect(Object.keys(bundleObj)).toEqual(["skills/foo/SKILL.md"]);
  });

  it("walks recursively to find nested skill folders", async () => {
    await writeFixture("skills/coding/code-review/SKILL.md", "# code-review");
    await writeFixture("skills/ops/incident-response/SKILL.md", "# incident");

    const out = join(tempDir, "out.ts");
    await bundle(join(tempDir, "skills"), out);
    const bundleObj = await importGeneratedBundle(out);

    expect(Object.keys(bundleObj).sort()).toEqual([
      "skills/coding/code-review/SKILL.md",
      "skills/ops/incident-response/SKILL.md",
    ]);
  });

  it("throws when no skill folders are found", async () => {
    await mkdir(join(tempDir, "skills"), { recursive: true });
    await expect(bundle(join(tempDir, "skills"), join(tempDir, "out.ts"))).rejects.toThrow(
      /No skill folders/,
    );
  });

  it("emits valid TypeScript that defines `skillsBundle`", async () => {
    const original = 'line\n\nwith "quotes" and ${interp} and \\backslash';
    await writeFixture("skills/foo/SKILL.md", original);

    const out = join(tempDir, "out.ts");
    await bundle(join(tempDir, "skills"), out);
    const src = await readFile(out, "utf-8");

    expect(src).toMatch(/^\/\/ Auto-generated by/);
    expect(src).toContain("export const skillsBundle = {");
    // Round-trip through the regex extractor confirms the JSON inside is parseable
    const parsed = await importGeneratedBundle(out);
    expect(parsed["skills/foo/SKILL.md"]).toBe(original);
  });
});
