import { readdir, readFile, writeFile } from "node:fs/promises";
import { basename, join, relative, sep } from "node:path";

const TEXT_EXTS = new Set([".md", ".txt", ".json", ".yaml", ".yml", ".svg", ".html", ".css"]);

const shouldSkipDir = (name: string): boolean => name.startsWith(".") || name === "node_modules";

const compare = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

const isTextExt = (file: string): boolean => {
  const base = basename(file);
  const dot = base.lastIndexOf(".");
  if (dot <= 0) return false;
  return TEXT_EXTS.has(base.slice(dot).toLowerCase());
};

async function* walk(dir: string): AsyncGenerator<string> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  entries.sort((a, b) => compare(a.name, b.name));
  for (const entry of entries) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (shouldSkipDir(entry.name)) continue;
      yield* walk(p);
    } else if (entry.isFile()) {
      yield p;
    }
  }
}

/**
 * Locate skill folders: directories containing a `SKILL.md` file directly inside them.
 * Recursion stops once a skill folder is found (skills don't nest).
 */
async function findSkillFolders(root: string): Promise<string[]> {
  const result: string[] = [];
  const go = async (dir: string): Promise<void> => {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    entries.sort((a, b) => compare(a.name, b.name));
    if (entries.some((e) => e.isFile() && e.name === "SKILL.md")) {
      result.push(dir);
      return;
    }
    for (const entry of entries) {
      if (entry.isDirectory() && !shouldSkipDir(entry.name)) {
        await go(join(dir, entry.name));
      }
    }
  };
  await go(root);
  return result;
}

async function collectSkillFiles(skillRoot: string): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  const skillMd = join(skillRoot, "SKILL.md");
  result[skillMd] = await readFile(skillMd, "utf-8");

  for (const subdir of ["references", "scripts", "assets"]) {
    for await (const file of walk(join(skillRoot, subdir))) {
      if (isTextExt(file)) {
        result[file] = await readFile(file, "utf-8");
      } else {
        console.warn(`[mastra-serverless-skills] skipping non-text file: ${file}`);
      }
    }
  }
  return result;
}

/**
 * Walk `inDir` for skill folders (folders containing `SKILL.md`), bundle their contents,
 * and write a TypeScript module to `outFile` exporting `skillsBundle` — a path → text
 * map matching the shape `BundledSkillSource` accepts.
 *
 * Output keys are `<basename(inDir)>/<relative path>` so they line up with the typical
 * Mastra config `skills: [<basename(inDir)>]`.
 */
export async function bundle(inDir: string, outFile: string): Promise<void> {
  const keyPrefix = basename(inDir);
  const skillFolders = await findSkillFolders(inDir);
  if (skillFolders.length === 0) {
    throw new Error(`No skill folders (containing SKILL.md) found under ${inDir}`);
  }

  const merged: Record<string, string> = {};
  for (const skillRoot of skillFolders) {
    const files = await collectSkillFiles(skillRoot);
    for (const [absPath, content] of Object.entries(files)) {
      const rel = relative(inDir, absPath).split(sep).join("/");
      merged[`${keyPrefix}/${rel}`] = content;
    }
  }

  const sortedKeys = Object.keys(merged).sort(compare);
  const sorted: Record<string, string> = {};
  for (const k of sortedKeys) sorted[k] = merged[k]!;

  const tsContent = `// Auto-generated by \`mastra-serverless-skills bundle\` — do not edit.
export const skillsBundle = ${JSON.stringify(sorted, null, 2)};
`;
  await writeFile(outFile, tsContent);
  console.log(
    `[mastra-serverless-skills] bundled ${sortedKeys.length} files from ${skillFolders.length} skill folder(s) → ${outFile}`,
  );
}
